#! /bin/sh

## startup

sxhkd &
nitrogen --set-zoom-fill ~/Pictures/wallpaper/wall.jpg &
polybar main &


## conf

bspc config border_width        2
bspc config window_gap          30
bspc config top_padding			29

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor -d home work admin misc

# bspc rule -a Gimp desktop=^8 follow=on floating=on
# bspc rule -a Chromium desktop=^2
# bspc rule -a mplayer2 floating=on
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
